version: '3.8'

services:
  # idRock Fraud Detection API
  idrock-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - API_PORT=3001
      - API_HOST=0.0.0.0
      - PROXYCHECK_API_KEY=${PROXYCHECK_API_KEY:-demo_key}
      - SQLITE_DB_PATH=/app/data/idrock.db
      - LOG_LEVEL=info
      - CORS_ORIGIN=http://localhost:8080,http://localhost:3000
    volumes:
      - ./data:/app/data
      - ./api/logs:/app/logs
    networks:
      - idrock-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # NexShop Demo E-commerce Store
  nexshop-store:
    build:
      context: ./demo-store
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_IDROCK_API_URL=http://localhost:3001/api
      - REACT_APP_ENVIRONMENT=production
      - GENERATE_SOURCEMAP=false
    networks:
      - idrock-network
    depends_on:
      idrock-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  idrock-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  app_data:
    driver: local